### ISSUE TITLE
Inline `@link` tags don't resolve correctly when used within `@params` and some `@see` tags.

### ISSUE THREAD

**Issue by toebeann** [citkane/typedoc-theme-yaf#11]
![image](https://user-images.githubusercontent.com/45315526/221352531-eaf33ebd-6cae-4a9c-96da-0eb6a1b16671.png)

The above `called` link, which is written in my tsdoc as `{@link call called}`, resolves to `/docs/dev/405`, which leads (ironically) to a 404 error. 

Elsewhere within the same class:

![image](https://user-images.githubusercontent.com/45315526/221352656-022fe21b-1005-4702-aebc-d04eea0a747e.png)

This `called` link (also written in tsdoc as `{@link call called}`) correctly points to `/docs/dev/?page=Function.call`.

Most examples I have found of inline `@link` tags not resolving correctly seem to be witin `@param` tags, For example, this resolves perfectly:
```ts
    /**
     * The endpoint at which the {@link Npc NPC procedure} is available to be {@link call called} or {@link notify notified}.
     */
```

However, this completely fails, none of the inline `@link` tags resolve correctly:
```ts
    /**
     * @param {T} callback The underlying {@link Callback callback} function which will be {@link call called} by clients.
     */
```

The problem also seems to affect `@see` tags on functions/class methods.

**Comment by citkane** [comment]
Thanks @toebeann 

FYI:

What the theme does in the back-end is convert all internal reference links to an "href" of the reflection id (ironically in your example, the id was 405).
The front-end then parses that back into a usable "href"  using `yafReflectionMap.json` in the `docs/data` directory.

This allows you to use links across modules in a mono-repo (something that the default theme can't do) using the notation `{@link mymodule.namespace.mything}`.

I had forgotten to parse the text strings for comments into the `yaf-navigation-link` web component, which does all this magic.
Fixed now!!
