### ISSUE TITLE
Links to absolute paths?

### ISSUE THREAD

**Issue by ilg-ul** [citkane/typedoc-theme-yaf#6]
I tried this theme (0.0.3), and it generally looked nice, but I have a problem when deploying it to GitHub Pages.

The site was generated on my local machine and it took me some time to discover that there are several symbolic links pointing to absolute paths, which fail when publishing on the GitHub Pages servers:

```console
ilg@wksi docs % find . -type l -exec ls -l '{}' ';'
lrwxr-xr-x  1 ilg  staff  83 Feb 18 21:54 ./stable -> /Users/ilg/My Files/WKS Projects/xpack.github/npm-modules/logger-ts.git/docs/v6.0.0
lrwxr-xr-x  1 ilg  staff  83 Feb 18 21:54 ./v6.0 -> /Users/ilg/My Files/WKS Projects/xpack.github/npm-modules/logger-ts.git/docs/v6.0.0
lrwxr-xr-x  1 ilg  staff  83 Feb 18 21:54 ./dev -> /Users/ilg/My Files/WKS Projects/xpack.github/npm-modules/logger-ts.git/docs/v6.0.0
ilg@wksi docs % 
```

Is there any reason for not using relative paths in these symbolic links?

**Comment by ilg-ul** [comment]
As a workaround, I added a shell script which I run after generating the site, to fix the absolute symlinks.

The deployment on GitHub Pages was successful! :-)

**Comment by ilg-ul** [comment]
Hi Michael,

It looks like this issue belongs to the `versions` plug-in, not the `yaf` one. If so, could you transfer it to the correct project?

**Comment by citkane** [comment]
Please open an issue on typedoc-plugin-versions

I am a co-maintainer there.
Following the example [github CID](https://github.com/citkane/typedoc-plugin-versions#cid) published there certainly does work as is.
Of course, this may be improved and your detailed input and suggestions will be appreciated.
