### ISSUE TITLE
Accessors do not have the link to the source file

### ISSUE THREAD

**Issue by ilg-ul** [citkane/typedoc-theme-yaf#8]
Here is a screen capture of an accessor:

![Screenshot 2023-02-19 at 15 21 22](https://user-images.githubusercontent.com/362732/219950890-5624f705-6c6d-4398-9254-75bd80b38391.png)

The same content, but with the default theme:

![Screenshot 2023-02-19 at 15 21 44](https://user-images.githubusercontent.com/362732/219950925-9335b541-f696-4261-be7c-e9498113c03d.png)

As it can be seen, the source line information, present with the default theme, is missing with the `yaf` theme.

**Comment by citkane** [comment]
Examining the issue,
Thanks for reporting.
