### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by ilg-ul** [citkane/typedoc-theme-yaf#9]
![Screenshot 2023-02-19 at 17 03 11](https://user-images.githubusercontent.com/362732/219956799-9e177743-d0a2-41a7-9b89-fdd970ec7038.png)

As it can be seen in the image, the font of the link to the source file is thin and (in my opinion) hard to read, with the underline being an aggravating factor. 

The same font seems to be used for the return type, but there readability is not that bad. 

I suggest a thinker font, and possibly to remove the underline.

Also, in the parameters table, the flag (rest) is not vertically aligned with the raw.

**Comment by citkane** [comment]
This is a subjective preference.
Please open a discussion thread if you wish.
